version: "3.8"

services:
    ibf-api-service:
        image: rodekruis/ibf-api-service
        ports:
            - 80:3000
        environment:
            - DB_TYPE=${DB_TYPE}
            - DB_HOST=${DB_HOST}
            - DB_PORT=${DB_PORT}
            - DB_DATABASE=${DB_DATABASE}
            - DB_USERNAME=${DB_USERNAME}
            - DB_PASSWORD=${DB_PASSWORD}
            - NODE_ENV=production
            - SECRET=${SECRET}
            - NG_PRODUCTION=true
            - NG_API_URL=${NG_API_URL}
            - NG_USE_MOCK_DATA=${NG_USE_MOCK_DATA}
            - NG_USE_SERVICE_WORKER=${NG_USE_SERVICE_WORKER}
            - NG_DEFAULT_COUNTRY_CODE=${NG_DEFAULT_COUNTRY_CODE}
            - NG_INITIAL_LAT=${NG_INITIAL_LAT}
            - NG_INITIAL_LNG=${NG_INITIAL_LNG}
        volumes:
            - api-service-root:/home/ibf/api-service
            - web-interface-root:/home/ibf/api-service/dist

    ibf-web-interface:
        command: npm start
        image: rodekruis/ibf-web-interface
        volumes:
            - web-interface-root:/home/node/app/www

    ibf-geoserver:
        image: kartoza/geoserver

volumes:
    api-service-root:
    web-interface-root:
